Repository googleapis/python-db-dtypes-pandas, pull requests merged in 2021-09, with the labels that each got.

#1 test: cleanup test sessions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/header-checker-lint.yml
  .kokoro/build.sh
  .kokoro/continuous/common.cfg
  .kokoro/continuous/continuous.cfg
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/presubmit.cfg
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic-head.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic-head.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic-head.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/samples/python3.9/common.cfg
  .kokoro/samples/python3.9/continuous.cfg
  .kokoro/samples/python3.9/periodic-head.cfg
  .kokoro/samples/python3.9/periodic.cfg
  .kokoro/samples/python3.9/presubmit.cfg
  .kokoro/test-samples-against-head.sh
  .kokoro/test-samples.sh
  .kokoro/trampoline.sh
  CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
  db_dtypes/version.py
  docs/_templates/layout.html
  docs/conf.py
  noxfile.py
  owlbot.py
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  setup.cfg
  setup.py
  testing/.gitignore
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
Labels: kokoro:force-run, cla: yes

#8 fix: support Pandas 0.24
  db_dtypes/core.py
  noxfile.py
  owlbot.py
  tests/unit/test_dtypes.py
Labels: cla: yes, api: bigquery

#9 test: No warnings
  db_dtypes/__init__.py
  db_dtypes/core.py
  db_dtypes/pandas_backports.py
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  tests/unit/test_dtypes.py
Labels: automerge, cla: yes, api: bigquery

#11 fix: support converting empty `time` Series to pyarrow Array
  db_dtypes/__init__.py
  tests/unit/test_arrow.py
  tests/unit/test_dtypes.py
Labels: cla: yes, api: bigquery
