Repository googleapis/python-db-dtypes-pandas, pull requests merged in 2025-03, with the labels that each got.

#325 fix: remove unbox json functionality from JSONArrowType
  db_dtypes/__init__.py
  db_dtypes/json.py
  tests/unit/test_json.py
Labels: api: bigquery, size: m

#329 chore: remove unused files
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/requirements.in
  .kokoro/docker/docs/requirements.txt
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/requirements.in
  .kokoro/requirements.txt
Labels: api: bigquery, size: xl

#331 fix: Updates noxfile with pip freeze and pandas 1.2
  noxfile.py
  setup.py
  testing/constraints-3.7.txt
Labels: api: bigquery, size: s

#333 fix: remove setup.cfg configuration for creating universal wheels
  setup.cfg
Labels: api: bigquery, size: s
